# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scenedescriber_pb2 as scenedescriber__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scenedescriber_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SceneServiceStub(object):
    """High-level service for your app
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/scenedescriber.SceneService/SayHello',
                request_serializer=scenedescriber__pb2.GreetRequest.SerializeToString,
                response_deserializer=scenedescriber__pb2.GreetReply.FromString,
                _registered_method=True)
        self.DescribeScene = channel.unary_unary(
                '/scenedescriber.SceneService/DescribeScene',
                request_serializer=scenedescriber__pb2.ImageRequest.SerializeToString,
                response_deserializer=scenedescriber__pb2.SceneReply.FromString,
                _registered_method=True)
        self.AskAboutScene = channel.unary_unary(
                '/scenedescriber.SceneService/AskAboutScene',
                request_serializer=scenedescriber__pb2.SceneQuestionRequest.SerializeToString,
                response_deserializer=scenedescriber__pb2.SceneReply.FromString,
                _registered_method=True)
        self.OcrImage = channel.unary_unary(
                '/scenedescriber.SceneService/OcrImage',
                request_serializer=scenedescriber__pb2.ImageRequest.SerializeToString,
                response_deserializer=scenedescriber__pb2.OcrReply.FromString,
                _registered_method=True)


class SceneServiceServicer(object):
    """High-level service for your app
    """

    def SayHello(self, request, context):
        """1. Simple greeting: client sends name, server responds with greeting message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeScene(self, request, context):
        """2. Describe the scene in an image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskAboutScene(self, request, context):
        """3. Ask a question about the scene/image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OcrImage(self, request, context):
        """4. OCR: extract text from an image of handwriting / print
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SceneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=scenedescriber__pb2.GreetRequest.FromString,
                    response_serializer=scenedescriber__pb2.GreetReply.SerializeToString,
            ),
            'DescribeScene': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeScene,
                    request_deserializer=scenedescriber__pb2.ImageRequest.FromString,
                    response_serializer=scenedescriber__pb2.SceneReply.SerializeToString,
            ),
            'AskAboutScene': grpc.unary_unary_rpc_method_handler(
                    servicer.AskAboutScene,
                    request_deserializer=scenedescriber__pb2.SceneQuestionRequest.FromString,
                    response_serializer=scenedescriber__pb2.SceneReply.SerializeToString,
            ),
            'OcrImage': grpc.unary_unary_rpc_method_handler(
                    servicer.OcrImage,
                    request_deserializer=scenedescriber__pb2.ImageRequest.FromString,
                    response_serializer=scenedescriber__pb2.OcrReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scenedescriber.SceneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scenedescriber.SceneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SceneService(object):
    """High-level service for your app
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scenedescriber.SceneService/SayHello',
            scenedescriber__pb2.GreetRequest.SerializeToString,
            scenedescriber__pb2.GreetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scenedescriber.SceneService/DescribeScene',
            scenedescriber__pb2.ImageRequest.SerializeToString,
            scenedescriber__pb2.SceneReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskAboutScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scenedescriber.SceneService/AskAboutScene',
            scenedescriber__pb2.SceneQuestionRequest.SerializeToString,
            scenedescriber__pb2.SceneReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OcrImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scenedescriber.SceneService/OcrImage',
            scenedescriber__pb2.ImageRequest.SerializeToString,
            scenedescriber__pb2.OcrReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
