# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scenedescriber.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scenedescriber.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14scenedescriber.proto\x12\x0escenedescriber\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nGreetReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"I\n\x14SceneQuestionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x10\n\x08question\x18\x03 \x01(\t\"\x1a\n\nSceneReply\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x18\n\x08OcrReply\x12\x0c\n\x04text\x18\x01 \x01(\t2\xb6\x02\n\x0cSceneService\x12\x44\n\x08SayHello\x12\x1c.scenedescriber.GreetRequest\x1a\x1a.scenedescriber.GreetReply\x12I\n\rDescribeScene\x12\x1c.scenedescriber.ImageRequest\x1a\x1a.scenedescriber.SceneReply\x12Q\n\rAskAboutScene\x12$.scenedescriber.SceneQuestionRequest\x1a\x1a.scenedescriber.SceneReply\x12\x42\n\x08OcrImage\x12\x1c.scenedescriber.ImageRequest\x1a\x18.scenedescriber.OcrReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scenedescriber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETREQUEST']._serialized_start=40
  _globals['_GREETREQUEST']._serialized_end=68
  _globals['_GREETREPLY']._serialized_start=70
  _globals['_GREETREPLY']._serialized_end=99
  _globals['_IMAGEREQUEST']._serialized_start=101
  _globals['_IMAGEREQUEST']._serialized_end=148
  _globals['_SCENEQUESTIONREQUEST']._serialized_start=150
  _globals['_SCENEQUESTIONREQUEST']._serialized_end=223
  _globals['_SCENEREPLY']._serialized_start=225
  _globals['_SCENEREPLY']._serialized_end=251
  _globals['_OCRREPLY']._serialized_start=253
  _globals['_OCRREPLY']._serialized_end=277
  _globals['_SCENESERVICE']._serialized_start=280
  _globals['_SCENESERVICE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
